#!/usr/bin/env node
/**
 * Build Doctor — pre-flight check before running `eas build`.
 *
 * Verifies:
 *   1. Working tree is clean (no uncommitted changes).
 *   2. Local branch is in sync with origin/main.
 *   3. build-info.ts is fresh and matches HEAD.
 *   4. Required icons exist with correct dimensions.
 *   5. No leftover android/ ios/ folders that would block prebuild.
 *
 * Exits non-zero if any critical check fails, so CI can gate `eas build`.
 *
 * Usage: `yarn build-doctor` or `node scripts/build-doctor.js`
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const ROOT = path.join(__dirname, "..");
let warnings = 0;
let errors = 0;

function safeExec(cmd, opts = {}) {
  try { return execSync(cmd, { stdio: ["pipe", "pipe", "pipe"], cwd: ROOT, ...opts }).toString().trim(); }
  catch (e) { return null; }
}

function ok(msg) { console.log(`  ✓ ${msg}`); }
function warn(msg) { console.log(`  ⚠ ${msg}`); warnings++; }
function err(msg) { console.log(`  ✗ ${msg}`); errors++; }
function section(title) { console.log(`\n— ${title} —`); }

console.log("\n================================================================");
console.log("🩺 CKD BUILD DOCTOR");
console.log("================================================================");

// 1. Git status
section("Git working tree");
const headCommit = safeExec("git rev-parse --short=8 HEAD") || "no-git";
const branch = safeExec("git rev-parse --abbrev-ref HEAD") || "no-git";
const dirty = safeExec("git status --porcelain") || "";
ok(`HEAD = ${headCommit} on ${branch}`);
if (dirty) {
  warn(`Uncommitted changes detected — these WILL ship in the APK:`);
  dirty.split("\n").slice(0, 10).forEach(l => console.log(`     ${l}`));
} else {
  ok("Working tree is clean");
}

// 2. Sync with origin
section("Sync with origin");
safeExec("git fetch origin --quiet");
const remote = safeExec(`git rev-parse --short=8 origin/${branch}`);
if (remote && remote !== headCommit) {
  err(`Local HEAD (${headCommit}) differs from origin/${branch} (${remote}). Run \`git pull\` first.`);
} else if (remote) {
  ok(`In sync with origin/${branch} @ ${remote}`);
} else {
  warn("Could not determine remote HEAD");
}

// 3. build-info.ts freshness
section("Build stamp");
const stampPath = path.join(ROOT, "src", "build-info.ts");
if (!fs.existsSync(stampPath)) {
  err(`src/build-info.ts MISSING — run \`yarn stamp-build\` first`);
} else {
  const content = fs.readFileSync(stampPath, "utf8");
  const stampCommit = (content.match(/commit:\s*"([^"]+)"/) || [])[1];
  ok(`Stamp file exists: commit=${stampCommit}`);
  if (stampCommit && !stampCommit.startsWith(headCommit)) {
    warn(`Stamp commit (${stampCommit}) ≠ HEAD (${headCommit}). Will be regenerated by EAS pre-install hook.`);
  }
}

// 4. Icon assets
section("Icon assets");
const expected = {
  "assets/images/icon.png": [1024, 1024],
  "assets/images/adaptive-icon.png": [1024, 1024],
  "assets/images/splash-icon.png": null, // any square size acceptable
  "assets/images/favicon.png": null,
};
let PNG = null;
try { PNG = require("pngjs").PNG; } catch {}

for (const [rel, expectedSize] of Object.entries(expected)) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) { err(`MISSING: ${rel}`); continue; }
  // Cheap dimension check from PNG header (bytes 16-23)
  try {
    const buf = fs.readFileSync(p);
    if (buf.slice(0, 8).toString("hex") !== "89504e470d0a1a0a") { warn(`${rel}: not a PNG`); continue; }
    const width = buf.readUInt32BE(16);
    const height = buf.readUInt32BE(20);
    if (expectedSize && (width !== expectedSize[0] || height !== expectedSize[1])) {
      err(`${rel}: ${width}x${height} (expected ${expectedSize[0]}x${expectedSize[1]})`);
    } else if (expectedSize) {
      ok(`${rel}: ${width}x${height}`);
    } else {
      ok(`${rel}: ${width}x${height}`);
    }
  } catch (e) {
    warn(`${rel}: could not read dimensions (${e.message})`);
  }
}

// 5. No leftover native folders
section("Managed workflow");
for (const dir of ["android", "ios"]) {
  if (fs.existsSync(path.join(ROOT, dir))) {
    err(`${dir}/ folder present — this will BLOCK \`expo prebuild\` from regenerating icons/splash. Delete it.`);
  } else {
    ok(`No ${dir}/ folder (prebuild will run fresh on EAS)`);
  }
}

// 6. EAS hooks present
section("EAS hooks");
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
const hooks = ["eas-build-pre-install", "eas-build-post-install", "postinstall"];
for (const h of hooks) {
  if (pkg.scripts && pkg.scripts[h]) ok(`scripts.${h} = ${pkg.scripts[h]}`);
  else warn(`scripts.${h} not defined`);
}

// 7. app.json versionCode + version
section("app.json");
const appJson = JSON.parse(fs.readFileSync(path.join(ROOT, "app.json"), "utf8"));
ok(`version = ${appJson.expo.version}`);
ok(`android.versionCode = ${appJson.expo.android?.versionCode}`);

// ---- Summary ----
console.log("\n================================================================");
if (errors === 0 && warnings === 0) {
  console.log(`✅ ALL CHECKS PASSED. Safe to run \`eas build --profile preview\`.`);
} else if (errors === 0) {
  console.log(`⚠ ${warnings} warning(s). Build can proceed but inspect above.`);
} else {
  console.log(`❌ ${errors} ERROR(S), ${warnings} warning(s). FIX BEFORE BUILDING.`);
}
console.log(`HEAD ➜ ${headCommit} on ${branch}`);
console.log("================================================================\n");

process.exit(errors > 0 ? 1 : 0);
