#!/usr/bin/env node
/**
 * Build Stamper — writes the current git commit + build metadata into
 * src/build-info.ts so the running app shows EXACTLY which commit was bundled.
 *
 * It runs in MULTIPLE places to survive EAS cache / dependency cache:
 *   1. `eas-build-pre-install`  — BEFORE npm install on EAS cloud builds.
 *   2. `eas-build-post-install` — AFTER npm install + prebuild on EAS builds
 *      (re-stamps so the latest commit/profile/build-id is always recorded).
 *   3. `postinstall`            — runs after every local `yarn install`.
 *   4. Manually via `yarn stamp-build` (used by `prestart` and `prebuild`).
 *
 * Data captured:
 *   - commit       : short git SHA (or EAS env fallback)
 *   - builtAt      : ISO timestamp of the stamp
 *   - profile      : EAS build profile (preview / production / development / local)
 *   - easBuildId   : EAS build identifier (cloud only)
 *   - versionCode  : Android versionCode read live from app.json
 *   - version      : app version from app.json
 *   - runner       : "eas-cloud" | "eas-local" | "local-dev"
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

function safeExec(cmd) {
  try {
    return execSync(cmd, { stdio: ["pipe", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
}

// ---- git commit (with multiple fallbacks) -----------------------------------
const easCommit = process.env.EAS_BUILD_GIT_COMMIT_HASH;
const gitCommit =
  safeExec("git rev-parse --short=8 HEAD") ||
  (easCommit ? easCommit.substring(0, 8) : "") ||
  (process.env.EAS_BUILD_ID ? `eas-${process.env.EAS_BUILD_ID.substring(0, 6)}` : "") ||
  "no-git";

const gitBranch =
  safeExec("git rev-parse --abbrev-ref HEAD") ||
  process.env.EAS_BUILD_GIT_BRANCH ||
  "unknown";

const gitDirty = safeExec("git status --porcelain") ? "+dirty" : "";

// ---- build metadata ---------------------------------------------------------
const builtAt = new Date().toISOString().substring(0, 19) + "Z";
const profile = process.env.EAS_BUILD_PROFILE || (process.env.EAS_BUILD ? "eas" : "local-dev");
const easBuildId = process.env.EAS_BUILD_ID || "";
const runner = process.env.EAS_BUILD === "true"
  ? "eas-cloud"
  : process.env.EAS_BUILD_RUNNER === "eas-build-local"
    ? "eas-local"
    : "local-dev";

// ---- read versionCode + version from app.json -------------------------------
let versionCode = 0;
let appVersion = "0.0.0";
try {
  const appJson = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "app.json"), "utf8"));
  versionCode = appJson?.expo?.android?.versionCode || 0;
  appVersion = appJson?.expo?.version || "0.0.0";
} catch (e) {
  console.warn("[stamp-build] could not read app.json:", e.message);
}

// ---- write build-info.ts ---------------------------------------------------
const out = `/**
 * AUTO-GENERATED by scripts/stamp-build.js — DO NOT edit manually.
 * Re-generated before every install / build / start. Safe to commit; the
 * pre-install + post-install EAS hooks will overwrite it during cloud builds.
 */
export const BUILD_INFO = {
  commit: "${gitCommit}${gitDirty}",
  branch: "${gitBranch}",
  builtAt: "${builtAt}",
  profile: "${profile}",
  runner: "${runner}",
  easBuildId: "${easBuildId}",
  versionCode: ${versionCode},
  version: "${appVersion}",
} as const;

export type BuildInfo = typeof BUILD_INFO;
`;

const target = path.join(__dirname, "..", "src", "build-info.ts");
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);

// ---- log a single-line fingerprint visible in EAS build logs ---------------
const fingerprint = `commit=${gitCommit}${gitDirty} branch=${gitBranch} v=${appVersion} vc=${versionCode} profile=${profile} runner=${runner} builtAt=${builtAt}`;
console.log("================================================================");
console.log(`[stamp-build] STAMPED ➜ ${fingerprint}`);
console.log(`[stamp-build] → wrote ${target}`);
console.log("================================================================");
