/**
 * AUTO-GENERATED by scripts/stamp-build.js — DO NOT edit manually.
 * Re-generated before every install / build / start. Safe to commit; the
 * pre-install + post-install EAS hooks will overwrite it during cloud builds.
 */
export const BUILD_INFO = {
  commit: "989df9f4+dirty",
  branch: "main",
  builtAt: "2026-05-28T08:04:00Z",
  profile: "local-dev",
  runner: "local-dev",
  easBuildId: "",
  versionCode: 7,
  version: "1.0.0",
} as const;

export type BuildInfo = typeof BUILD_INFO;
